---
title: "Boxplots for Clustered Toxicological Data with toxbox"
author: "Philip Pallmann"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Boxplots for Clustered Toxicological Data with toxbox}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r message=FALSE}
library("knitr")
library("toxbox")
```

We use the rat pup data from package `WWGbook` and reorder the `treatment` factor:

```{r}
library("WWGbook")
data(ratpup)
ratpup$treatment <- factor(ratpup$treatment, levels=c("Control", "Low", "High"))
```

We plot the data assuming the Dunnett p-values for comparisons to the negative control were 0.07 and 0.04.

```{r fig.width=7, fig.height=5}
boxclust(data=ratpup, outcome="weight", treatment="treatment", cluster="litter",
         covariate="sex", xlabel="", ylabel="Pup weight [g]\n", psize=1.5,
         hjitter=0.01, pneg=c(0.07, 0.04), stars=TRUE, white=TRUE)
```

We plot the data assuming high were the positive control, and the p-values for comparisons to the negative and positive control were 0.0008 and 0.12, respectively.

```{r fig.width=7, fig.height=5}
boxclust(data=ratpup, outcome="weight", treatment="treatment", cluster="litter",
         covariate="sex", xlabel="", ylabel="Pup weight [g]\n", psize=1.5,
         hjitter=0.01, pneg=0.0008, ppos=0.12, white=TRUE)
```
